kind: Service
apiVersion: v1
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
  selector:
    app: ftps
  ports:
    - port: 21
      protocol: TCP
      targetPort: 21
      name: ftps
    - port: 30000
      name: first
      targetPort: 30000
    - port: 30001
      name: second
      targetPort: 30001
  type: LoadBalancer
 
 
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 30000
            - containerPort: 30001
  selector:
    matchLabels:
      app: ftps 